name: Deploy Infrastructure

on:
  workflow_dispatch:
  
env:
  BASE_NAME: aca-dev-001
  BASE_NAME_2: aca-dev  
  LOCATION: uksouth

jobs:
  deploy-infrastructure:
    name: "Terraform Infrastructure Change Management"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: ./

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2