name: Deploy Infrastructure

on:
  workflow_dispatch:
  
env:
  BASE_NAME: aca-dev-001
  BASE_NAME_2: aca-dev  
  LOCATION: uksouth

jobs:
  deploy-infrastructure:
    name: "Terraform Infrastructure Change Management"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        # We keep Terraform files in the terraform directory.
        working-directory: ./

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.4

      - name: Terraform init
        id: init
        run: terraform init          